vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        article:
            uri_prefix: /images/articles/
            upload_destination: '%kernel.project_dir%/public/images/articles'
            # Will rename uploaded files using a uniqueid as a suffix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
